config:
  target: https://fasta-test.onrender.com
  plugins:
    ensure: {}
  phases:
    - duration: 30
      arrivalRate: 100
      name: "sustained load"
  payload:
    path: "./auth.csv"
    fields:
      - "email"
      - "password"
  ensure:
    thresholds:
      - "http.response_time.p99": 50

scenarios:
  - name: "Sign up"
    flow:
      - post:
          url: "/api/auth/register"
          json:
            first_name: "John"
            last_name: "Doe"
            email: "Dovie32@example.net"
            password: "@RwkWspKUKy1"
          capture:
            - json: "$.email"
              as: "email"
            - json: "$.confirmation_code"
              as: "confirmation_code"
      - get:
          url: "/api/auth/confirm/{{ confirmation_code }}"
      - post:
          url: "/api/auth/resend-confirm"
          json:
            email: "Dovie32@example.net"
      - post:
          url: "/api/auth/login"
          json:
            email: "Dovie32@example.net"
            password: "Dovie32@example.net"


  - name: "wallet"
    flow:
      - post:
          url: "/api/auth/login"
          json:
            email: "Dovie32@example.net"
            password: "Dovie32@example.net"
          capture:
            - token: "$.token"
              as: "token"
      - post:
          url: "/api/wallet"
          headers:
            Authorization: "Bearer {{ token }}"
      - post:
          url: "/api/wallet/create_pin"
          headers:
            Authorization: "Bearer {{ token }}"
          json:
            transaction_pin: "3456"
      - get:
          url: "/api/wallet"
          headers:
            Authorization: "Bearer {{ token }}"

  - name: "donation"
    flow:
      - post:
          url: "/api/auth/login"
          json:
            email: "Dovie32@example.net"
            password: "Dovie32@example.net"
          capture:
            - token: "$.token"
              as: "token"
      - get:
          url: "/api/wallet"
          headers:
            Authorization: "Bearer {{ token }}"
          capture:
            - beneficiary_id: "$.beneficiary_id"
              as: "beneficiary_id"
      - get:
          url: "/api/donation/verify_beneficiary"
          json:
            email: "{{ beneficiary_id }}"
          capture:
            - wallet_id : "$.wallet_id"
              as: "beneficiary_id"
      - post:
          url: "/api/wallet"
          headers:
            Authorization: "Bearer {{ token }}"
      - get:
          url: "/api/wallet"
          headers:
            Authorization: "Bearer {{ token }}"
          capture:
            - wallet_id : "$.wallet_id"
              as: "donor_id"
      - get:
          url: "/api/donation/{{ donor_id }}"
      - get:
          url: "/api/donation"

hooks:
  - beforeRequest: "timestamp"
  - afterResponse: "timestamp"

  # Calculate and log the p99 response time
  - function: "calculateP99"
    capture: "p99"
    using:
      compare: "jsonpath"
      expect: "$.timestamp"
      jsonpath: "$[*].timestamp"
      percentile: 99

  # Log the p99 response time
  - log: "p99: {{ p99 }} ms"
